    //*** Italian TEMPLATE
  sCancelCaptionI = 'Annulla';
  CaptionsI: array[TMsgDlgType] of string = ('Attenzione', 'Errore',
    'Informazione', 'Conferma', '');


  ButtonCaptionsI: array[TMsgDlgBtn] of string = (
    'Si', 'No', 'OK', 'Annulla', 'Termina', 'Riprova', 'Ignora',
    'Tutti', 'No a tutti', 'Si a tutti', 'Aiuto!'{$IF CompilerVersion >= 21}, 'Chiudi'{$ENDIF});

  //*** English TEMPLATE
  sCancelCaptionE = 'Cancel';
  CaptionsE: array[TMsgDlgType] of string = ('Warning', 'Error',
    'Information', 'Confirm', '');

  ButtonCaptionsE: array[TMsgDlgBtn] of string = (
    'Yes', 'No', 'OK', 'Cancel', 'Abort', 'Retry', 'Ignore', 'All',
    'No to all', 'Yes to all', 'Help'{$IF CompilerVersion >= 21}, 'Close'{$ENDIF});

  //*** Russian
  sCancelCaptionR = 'Îòìåíà';
  CaptionsR: array[TMsgDlgType] of string = ('Ïðåäóïðåæäåíèå', 'Îøèáêà',
    'Èíôîðìàöèÿ', 'Ïîäòâåðæäåíèå', '');

  ButtonCaptionsR: array[TMsgDlgBtn] of string = (
    'Äà', 'Íåò', 'OK', 'Îòìåíà', 'Ñòîï', 'Ïîâòîð', 'Ïðîïóñòèòü', 'Âñå',
    'Íåò äëÿ âñåõ', 'Äà äëÿ âñåõ', 'Ñïðàâêà'{$IF CompilerVersion >= 21}, 'Close'{$ENDIF});

  //*** Portuguese
  sCancelCaptionP = 'Cancela';
  CaptionsP: array[TMsgDlgType] of string = ('Aviso', 'Erro',
    'Informação', 'Confirmação', '');

  ButtonCaptionsP: array[TMsgDlgBtn] of string = (
    'Sim', 'Não', 'OK', 'Cancela', 'Aborta', 'Tenta Novamente', 'Ignora',
    'Tudo',
    'Não para Tudo', 'Sim para Tudo', 'Ajuda'{$IF CompilerVersion >= 21}, 'Chiudi'{$ENDIF});

  //*** Turkish
  sCancelCaptionT = 'Vazgeç';
  CaptionsT: array[TMsgDlgType] of string = ('Uyarý', 'Hata',
    'Bilgi', 'Doðrulama', '');

  ButtonCaptionsT: array[TMsgDlgBtn] of string = (
    'Evet', 'Hayýr', 'TAMAM', 'Vazgeç', 'Durdur', 'Tekrar', 'Ýptal', 'Hepsi',
    'Hepsine hayýr', 'Hepsine evet', 'Yardým'{$IF CompilerVersion >= 21}, 'Close'{$ENDIF});

  //*** German
  sCancelCaptionG = 'Abbrechen';
  CaptionsG: array[TMsgDlgType] of string = ('Warnung', 'Fehler',
    'Information', 'Bestätigung', '');

  ButtonCaptionsG: array[TMsgDlgBtn] of string = (
    'Ja', 'Nein', 'OK', 'Abbrechen', 'Abbrechen', 'Wiederholen', 'Ignorieren',
    'Alle',
    'Nein zu allen', 'Ja zu allen', 'Hilfe'{$IF CompilerVersion >= 21}, 'Close'{$ENDIF});


  //*** Dutch
  sCancelCaptionD = 'Annuleren';
  CaptionsD: array[TMsgDlgType] of string = ('Waarschuwing', 'Fout',
    'Informatie', 'Bevestiging', '');

  ButtonCaptionsD: array[TMsgDlgBtn] of string = (
    'Ja', 'Nee', 'OK', 'Annuleren', 'Afbreken', 'Herhalen', 'Negeren', 'Alles',
    'Nee op alles', 'Ja op alles', '?'{$IF CompilerVersion >= 21}, 'Close'{$ENDIF});

  //*** French
  sCancelCaptionF = 'Annuler';
  CaptionsF: array[TMsgDlgType] of string = ('Avertissement', 'Erreur',
    'Information', 'Confirmation', '');

  ButtonCaptionsF: array[TMsgDlgBtn] of string = (
    'Oui', 'Non', 'OK', 'Annuler', 'Abandonner', 'Réessayer', 'Ignorer', 'Tout',
    'Non pour tous', 'Oui pour tous', 'Aide'{$IF CompilerVersion >= 21}, 'Close'{$ENDIF});

  //*** Greek
  sCancelCaptionGr = '¢êõñï';
  CaptionsGr: array[TMsgDlgType] of string = ('Ðñïóï÷Þ!', 'ËÜèïò',
    'Ðëçñïöïñßá', 'Åðéâåâáßùóç', '');

  ButtonCaptionsGr: array[TMsgDlgBtn] of string = (
    'Íáß', '¼÷é', 'ÅíôÜîåé', '¢êõñï', '¢êýñùóç', 'ÐñïóðÜèåéá', 'Áãíþçóç', '¼ëá',
    '¼÷é óå üëá', 'Íáß óå üëá', 'ÂïÞèåéá'{$IF CompilerVersion >= 21}, 'Close'{$ENDIF});

  //*** Spanish
  sCancelCaptionS = 'Cancelar';
  CaptionsS: array[TMsgDlgType] of string = ('Precaución', 'Error',
    'Información', 'Confirmación', '');

  ButtonCaptionsS: array[TMsgDlgBtn] of string = (
    'Si', 'No', 'OK', 'Cancelar', 'Abortar', 'Reintentar', 'Ignorar', 'Todo',
    'No a todo', 'Si a todo', 'Ayuda'{$IF CompilerVersion >= 21}, 'Close'{$ENDIF});

